### ISSUE TITLE
Dropping hp bar bigger than hp after healing

### ISSUE THREAD

**Issue by wangenau** [bilbolPrime/SPD#2]
If the hp bar is dropping and you heal yourself with a heal potion before the dropping bar is away, the dropping bar is bigger than it should be.
The bug can easy reproduced while walking in toxic gas.
Its seems that the dropping mana bar does not have the same issue.
This bug was found in build 47. Testet on android 4.4 with 240 dpi.
![screenshot_2017-02-04-13-13-47](https://cloud.githubusercontent.com/assets/15988797/22619371/9fe852cc-eaf3-11e6-85f0-910b3c0dcaa4.png)

**Comment by bilbolPrime** [comment]
Thank you for the comment. Yes I have noticed this as well

Will check the issue in new build

**Comment by bilbolPrime** [comment]
https://github.com/bilbolPrime/SPD/commit/207a2943629365ea0fd335cf6b6cacb7f7ad8779

Will publish to store shortly. 0.3.6 Build 56

Thank you for your report :)
