### ISSUE TITLE
Files appear to be missing.

### ISSUE THREAD

**Issue by demasu** [bilbolPrime/SPD#4]
When attempting to build this myself (after changing a few things to attempt to get it to work with gradle), it seems like two skill files are missing.

1. Spark for the Mage
2. DoubleStab for the Rouge

Additionally, looking through the commit history, the references to the missing skills were added in commit 062014fa where the skills SummonCrab and DeadEye were removed for build 67. Am I missing those class declarations, or are they missing from the repo?

![screen shot 2018-08-27 at 6 12 17 pm](https://user-images.githubusercontent.com/3308274/44691561-d42c0780-aa24-11e8-8d38-8a594f5d8bb2.png)
![screen shot 2018-08-27 at 6 12 21 pm](https://user-images.githubusercontent.com/3308274/44691563-d5f5cb00-aa24-11e8-8f8d-5f16e2269bcd.png)

**Comment by bilbolPrime** [comment]
Hello,

Sorry for the long delay

Missing files added in commit [2f1d54ba974e6131ca5906feb6e28afcb645fe3d](https://github.com/bilbolPrime/SPD/commit/2f1d54ba974e6131ca5906feb6e28afcb645fe3d)
