### ISSUE TITLE
Second Quickslot disappears when switching levels

### ISSUE THREAD

**Issue by ginsterbusch** [bilbolPrime/SPD#6]
Looks like the second quickslot disappears whenever one goes one level up or down.

SPD version: v0.4.5 (Build 91)
Android: 7
System: Honor 9

cu, w0lf.

**Comment by bilbolPrime** [comment]
Hello,

I believe this only happens if you don't have anything assigned to the slot. Thank you for pointing it out though, this should be saved in game settings.

**Comment by bilbolPrime** [comment]
fixed
